---
- name: Uninstall packages
  hosts: webservers
  become: true
  vars:
    packages:
      - htop
      - wget
      - tree
      - unzip
      - git

  tasks:
    - name: Uninstall packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        " {{ packages }}"
